name: react_surge
on: 
  push:
    branches:
      - react_app_deploy_2
jobs:
  build_estatics:
    name: build_estatics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: npm install
        run: npm run build
        working-directory: ./surge_app
      - name: artifact_generated
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./surge_app/build
    deploy_job:
      runs-on: ubuntu-latest
      needs: build_estatics
      steps:
        - name: artifact_download
          uses: actions/download-artifact@v2
          with: 
            name: artifact_generated
        - name: deploy_artifact
          uses: dswistowski/surge-sh-action@v1
          with:
            domain: xema_maestre.surge.sh
            project: .
            login: ${{ secrets.surge_login }}
            token: ${{ secrets.surge_token }}
            