name: Bot telegram
on: 
  push:
    branches:
      - send_telegram_action
jobs:
  send_telegram_bot:
    name: send_telegram_bot 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send message
        uses: ./.github/actions/send_telegram_action
        with:
          token_father: ${{ secrets.TELEGRAM_BOT_PRUEBA_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_ID_CHAT_PRUEBA }}
          name: "Xema"
